# Run at EVERY build (custom target jamrack_git_hash): writes OUT with the
# short git hash of the sources being compiled, "+" when tracked files have
# uncommitted changes. The file is rewritten only when its content changes,
# so an unchanged hash recompiles nothing.
#   cmake -DSRC=<repo dir> -DOUT=<header> -P git_hash.cmake
find_package(Git QUIET)
set(hash "nogit")
if(GIT_FOUND)
  execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
                  WORKING_DIRECTORY "${SRC}" OUTPUT_VARIABLE h RESULT_VARIABLE r
                  OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  if(r EQUAL 0 AND h)
    set(hash "${h}")
    execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
                    WORKING_DIRECTORY "${SRC}" OUTPUT_VARIABLE dirty
                    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
    if(dirty)
      string(APPEND hash "+")
    endif()
  endif()
endif()
set(content "// Generated by plugin/cmake/git_hash.cmake at build time. Do not edit.\n#pragma once\n#define JAMRACK_GIT_HASH \"${hash}\"\n")
if(EXISTS "${OUT}")
  file(READ "${OUT}" old)
else()
  set(old "")
endif()
if(NOT old STREQUAL content)
  file(WRITE "${OUT}" "${content}")
  message(STATUS "JAMRACK build hash: ${hash}")
endif()
