#!/usr/bin/env python3
"""Regenerates js/audio/guitar/poly/profile.js from test/poly/bank/profile-dev.json
(the B law and the partial profiles the browser needs to build the generic bank).

    python3 test/poly/export-profile.py
"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
s = json.load(open(os.path.join(HERE, 'bank', 'profile-dev.json')))
law = [[s['B_law'][str(i)]['B_open_fit'], s['B_law'][str(i)]['slope_per_6_frets']] for i in range(6)]
def fmt(rows, nd):
    return '[\n' + ',\n'.join('    [' + ', '.join(f'{x:.{nd}g}' for x in r) + ']' for r in rows) + ',\n  ]'
out = f"""// Measured guitar profile behind the generic POLY template bank.
// Generated by test/poly/export-profile.py from test/poly/bank/profile-dev.json
// (test/poly/bank/extract.py on the 120 GuitarSet takes of the DEV players
// 00 and 03, debleeded hexaphonic stems). Do not edit by hand.
//
// Strings are indexed 0..5 = low E .. high E.
//   B_LAW[s]    = [B_open_fit, slope_per_6_frets]: the inharmonicity of fret f
//                 is B_open_fit * 2 ** (f * slope / 6)
//   PROF_ATT[s] = median partial-amplitude profile of the attack (partials
//                 1..40, unit L2 over the partials): the amplitudes a_n of the
//                 template renderer
//   PROF_DEC[s] = same for the decay phase (kept for a future 'dec' bank)

export const B_LAW = {fmt(law, 17)};

export const PROF_ATT = {fmt(s['prof_att'], 9)};

export const PROF_DEC = {fmt(s['prof_dec'], 9)};
"""
dst = os.path.join(ROOT, 'js', 'audio', 'guitar', 'poly', 'profile.js')
open(dst, 'w', encoding='utf-8').write(out)
print('wrote', dst)
