#!/usr/bin/env python3
"""Builds exactly-labelled polyphony for the POLY prototype (jalon 1 bis and
the improvement session of docs/polyphonic-plan.md, section 12): (1) by
MIXING solo GuitarSet takes of different players (real pickup signal, exact
labels, mostly notes over sustained notes of another player), and (2) by
summing 2 or 3 STRINGS of the debleeded hexaphonic stems of the comp takes
(strummed dyads and triads with simultaneous onsets, exact labels).

  python3 test/poly/make_mixes.py --guitarset <dir> --out <mixdir> [--split test/poly/split.json] [--write-split]

SPLIT BY PLAYER (test/poly/split.json). The thresholds are tuned on DEV and
reported on TEST; a mix never crosses the split, so no TEST audio is ever
heard during tuning (the first prototype's split was contaminated this way):
  DEV  = players 00 and 03 (their 8 solo and 4 comp takes of test/takes.json)
  TEST = players 01, 02, 04 and 05 (16 solo, 8 comp)
Mixes, within one split whose solo takes L are listed in test/takes.json
order (4 per player, player blocks b = 0..nb-1, i = 4 b + k):
  mix2: (L[i], L[4 ((b+1) mod nb) + (k+1) mod 4])            for i = 0..n-1
        -> 8 DEV mixes, 16 TEST mixes, the two takes of different players
  mix3: (L[i], L[4 ((b+1) mod nb) + (k+1) mod 4],
               L[4 ((b+2) mod nb) + (k+2) mod 4])            for i = 0..n/2-1
        -> 4 DEV mixes (DEV has two players, so the third take is another
           take of the first player), 8 TEST mixes of three players
  hex2: for each comp take, strings (1, 2) A+D, (3, 4) G+B, (0, 4) E2+B3
        (channel 0 = low E = data_source 0)  -> 12 DEV, 24 TEST
  hex3: strings (0, 1, 2) E+A+D, (3, 4, 5) G+B+E4                -> 8 DEV, 16 TEST
Mix names use the index of each take in the solo list of test/takes.json
(mix2_00+13 = takes 0 and 13); hex names carry the take and the strings.
--write-split regenerates split.json from this rule (and fails if an existing
file differs), otherwise the file is read and its recipe is built as is.

GAINS. Solo mixes: each constituent is scaled to -26 dBFS RMS (about the
median of the solo list) before the unit-gain sum ("equal gains"); the mix is
truncated to the shortest take; if the sum peaks above 0.98 the whole mix is
scaled down (the labels do not depend on level). Reference = union of the
note_midi annotations of the constituents (notes cut at the truncation
point, notes starting after it dropped). Hex remixes: the selected channels
of audio_hex-pickup_debleeded/<take>_hex_cln.wav are summed with unit gains
and scaled by rms(mono mix) / rms(sum of the six stems) of the take, so that
each string sits at the level it has in the mono mix (then the same 0.98
peak rule); the reference is the note_midi annotations of those strings.

The output directory mimics GuitarSet so that test/score.py and
test/dump-events.mjs run unchanged on it:
  <mixdir>/annotation/<name>.jams, <mixdir>/audio_mono-pickup_mix/<name>_mix.wav
plus symlinks to the original solo and comp takes, and <mixdir>/takes.json
with the lists solo, comp, mix2, mix3, hex2, hex3 (DEV + TEST, so that
score.py measures the annotation lag on the full solo list), dev_<set> and
test_<set>, and the recipe of every mix with the gains actually applied.
"""
import argparse
import json
import os

import numpy as np
import soundfile as sf

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET_RMS_DB = -26.0
PEAK_MAX = 0.98
DEV_PLAYERS = ('00', '03')
TEST_PLAYERS = ('01', '02', '04', '05')
HEX_SUBSETS = {'hex2': [(1, 2), (3, 4), (0, 4)], 'hex3': [(0, 1, 2), (3, 4, 5)]}
SETS = ('solo', 'comp', 'mix2', 'mix3', 'hex2', 'hex3')


def read_jams(path):
    with open(path) as f:
        return json.load(f)


def mix_name(kind, idx):
    return f"{kind}_{'+'.join(f'{i:02d}' for i in idx)}"


def hex_name(kind, take, sub):
    return f"{kind}_{take}_s{''.join(str(i) for i in sub)}"


def make_split(takes):
    """The split by player and the mix recipe, from the rule in the docstring."""
    solo, comp = takes['solo'], takes['comp']
    out = {'dev_players': list(DEV_PLAYERS), 'test_players': list(TEST_PLAYERS), 'dev': {}, 'test': {}, 'recipe': {}}
    out['_comment'] = ['Split by player of the POLY bench (generated by test/poly/make_mixes.py --write-split; do not edit by hand).',
                       'DEV = players 00 and 03, TEST = players 01, 02, 04, 05; every mix is built from takes of ONE split.',
                       'mix2/mix3: solo takes of test/takes.json (names carry their indices), mixed at -26 dBFS RMS each, unit-gain sum.',
                       'hex2/hex3: 2 or 3 debleeded strings of one comp take, scaled by rms(mono mix) / rms(sum of the 6 stems).',
                       'See the docstring of make_mixes.py for the exact rule.']
    for split, players in (('dev', DEV_PLAYERS), ('test', TEST_PLAYERS)):
        idx = [i for i, t in enumerate(solo) if t[:2] in players]
        n, nb = len(idx), len(idx) // 4
        assert n == 4 * nb
        lists = {'solo': [solo[i] for i in idx], 'comp': [t for t in comp if t[:2] in players],
                 'mix2': [], 'mix3': [], 'hex2': [], 'hex3': []}
        for i in range(n):
            b, k = divmod(i, 4)
            j = 4 * ((b + 1) % nb) + (k + 1) % 4
            combo = (idx[i], idx[j])
            name = mix_name('mix2', combo)
            lists['mix2'].append(name)
            out['recipe'][name] = {'kind': 'mix', 'sources': [solo[c] for c in combo]}
        for i in range(n // 2):
            b, k = divmod(i, 4)
            j = 4 * ((b + 1) % nb) + (k + 1) % 4
            l = 4 * ((b + 2) % nb) + (k + 2) % 4
            combo = (idx[i], idx[j], idx[l])
            assert len(set(combo)) == 3
            name = mix_name('mix3', combo)
            lists['mix3'].append(name)
            out['recipe'][name] = {'kind': 'mix', 'sources': [solo[c] for c in combo]}
        for take in lists['comp']:
            for kind, subsets in HEX_SUBSETS.items():
                for sub in subsets:
                    name = hex_name(kind, take, sub)
                    lists[kind].append(name)
                    out['recipe'][name] = {'kind': 'hex', 'source': take, 'strings': list(sub)}
        out[split] = lists
    return out


def write_wav(path, x, sr):
    sf.write(path, np.clip(x, -1, 1).astype(np.float32), sr, subtype='PCM_16')


def build_mix(a, name, sources, ann_dir, wav_dir):
    xs, jams, gains = [], [], []
    for n in sources:
        x, sr = sf.read(os.path.join(a.guitarset, 'audio_mono-pickup_mix', n + '_mix.wav'), dtype='float64', always_2d=True)
        x = x[:, 0]
        g = 10 ** (TARGET_RMS_DB / 20) / np.sqrt(np.mean(x ** 2))
        xs.append(x * g)
        gains.append(float(g))
        jams.append(read_jams(os.path.join(a.guitarset, 'annotation', n + '.jams')))
    L = min(len(x) for x in xs)
    mix = sum(x[:L] for x in xs)
    dur = L / sr
    peak = float(np.abs(mix).max())
    post = 1.0 if peak <= PEAK_MAX else PEAK_MAX / peak
    mix *= post
    write_wav(os.path.join(wav_dir, name + '_mix.wav'), mix, sr)
    out = {'annotations': [], 'file_metadata': {'duration': dur, 'title': name, 'sources': sources, 'gains': gains, 'post_gain': post}}
    for j in jams:
        for ann in j['annotations']:
            if ann['namespace'] != 'note_midi':
                continue
            data = []
            for d in ann['data']:
                if d['time'] >= dur:
                    continue
                dd = dict(d)
                dd['duration'] = min(d['duration'], dur - d['time'])
                data.append(dd)
            out['annotations'].append({'namespace': 'note_midi', 'annotation_metadata': ann['annotation_metadata'], 'data': data})
    with open(os.path.join(ann_dir, name + '.jams'), 'w') as f:
        json.dump(out, f)
    notes = sum(len(x['data']) for x in out['annotations'])
    print(f'{name}: {dur:.1f} s, {notes} notes, gains {" ".join(f"{20 * np.log10(g):+.1f}" for g in gains)} dB, peak {peak:.2f}, post {post:.2f}')
    return {'kind': 'mix', 'sources': sources, 'gains_db': [20 * np.log10(g) for g in gains], 'post_gain': post, 'duration': dur, 'notes': notes}


def build_hex(a, take, subsets, ann_dir, wav_dir):
    """All the hex remixes of one comp take: {name: recipe}."""
    hexdir = os.path.join(a.guitarset, 'audio_hex-pickup_debleeded')
    hx, sr = sf.read(os.path.join(hexdir, take + '_hex_cln.wav'), dtype='float64', always_2d=True)
    mono, _ = sf.read(os.path.join(a.guitarset, 'audio_mono-pickup_mix', take + '_mix.wav'), dtype='float64', always_2d=True)
    n = min(len(hx), len(mono))
    g = np.sqrt(np.mean(mono[:n, 0] ** 2)) / np.sqrt(np.mean(hx[:n].sum(axis=1) ** 2))
    j = read_jams(os.path.join(a.guitarset, 'annotation', take + '.jams'))
    res = {}
    for name, sub in subsets:
        mix = hx[:n, list(sub)].sum(axis=1) * g
        peak = float(np.abs(mix).max())
        post = 1.0 if peak <= PEAK_MAX else PEAK_MAX / peak
        mix *= post
        write_wav(os.path.join(wav_dir, name + '_mix.wav'), mix, sr)
        out = {'annotations': [ann for ann in j['annotations'] if ann['namespace'] == 'note_midi'
                               and int(ann['annotation_metadata'].get('data_source') or 0) in sub],
               'file_metadata': {'duration': n / sr, 'title': name, 'source': take, 'strings': list(sub), 'gain': float(g * post)}}
        with open(os.path.join(ann_dir, name + '.jams'), 'w') as f:
            json.dump(out, f)
        notes = sum(len(x['data']) for x in out['annotations'])
        res[name] = {'kind': 'hex', 'source': take, 'strings': list(sub), 'gain_db': 20 * np.log10(g * post), 'duration': n / sr, 'notes': notes}
        print(f'{name}: {n / sr:.1f} s, {notes} notes, gain {20 * np.log10(g):+.1f} dB, post {post:.2f}')
    return res


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--guitarset', required=True)
    ap.add_argument('--takes', default=os.path.join(HERE, '..', 'takes.json'))
    ap.add_argument('--split', default=os.path.join(HERE, 'split.json'), help='split by player (read, or written with --write-split)')
    ap.add_argument('--write-split', action='store_true', help='(re)generate --split from the rule, then build')
    ap.add_argument('--out', required=True)
    a = ap.parse_args()
    takes = json.load(open(a.takes))
    if a.write_split or not os.path.exists(a.split):
        split = make_split(takes)
        if os.path.exists(a.split):
            old = json.load(open(a.split))
            if {k: v for k, v in old.items() if k != '_comment'} != {k: v for k, v in split.items() if k != '_comment'}:
                raise SystemExit(f'{a.split} differs from the rule: delete it first if the rule changed, and re-score everything')
        with open(a.split, 'w') as f:
            json.dump(split, f, indent=1)
        print(f'wrote {a.split}')
    split = json.load(open(a.split))
    ann_dir = os.path.join(a.out, 'annotation')
    wav_dir = os.path.join(a.out, 'audio_mono-pickup_mix')
    os.makedirs(ann_dir, exist_ok=True)
    os.makedirs(wav_dir, exist_ok=True)
    for t in takes['solo'] + takes['comp']:
        for sub, fn in (('annotation', t + '.jams'), ('audio_mono-pickup_mix', t + '_mix.wav')):
            dst = os.path.join(a.out, sub, fn)
            if not os.path.lexists(dst):
                os.symlink(os.path.abspath(os.path.join(a.guitarset, sub, fn)), dst)
    recipe = {}
    for name, r in split['recipe'].items():
        if r['kind'] == 'mix':
            recipe[name] = build_mix(a, name, r['sources'], ann_dir, wav_dir)
    by_take = {}
    for name, r in split['recipe'].items():
        if r['kind'] == 'hex':
            by_take.setdefault(r['source'], []).append((name, tuple(r['strings'])))
    for take, subsets in by_take.items():
        recipe.update(build_hex(a, take, subsets, ann_dir, wav_dir))
    lists = {'_comment': ['Generated by test/poly/make_mixes.py from test/poly/split.json (split by player); see its docstring.'],
             'split': a.split}
    for k in SETS:
        lists[k] = split['dev'][k] + split['test'][k]
    for k in SETS:
        lists['dev_' + k] = split['dev'][k]
        lists['test_' + k] = split['test'][k]
    lists['dev'] = split['dev']
    lists['test'] = split['test']
    lists['recipe'] = recipe
    with open(os.path.join(a.out, 'takes.json'), 'w') as f:
        json.dump(lists, f, indent=1)
    for s in ('dev', 'test'):
        print(s + ': ' + ', '.join(f"{k} {len(split[s][k])}" for k in SETS))


if __name__ == '__main__':
    main()
