#include "JamrackLookAndFeel.h"

#include "MidPluckAssets.h"   // generated by juce_add_binary_data (target midpluck_ui_assets)

#include <cmath>
#include <vector>

namespace jamrack
{
    //==============================================================================
    Fonts::Fonts()
    {
        using namespace MidPluckAssets;
        const auto make = [] (const char* data, int size)
        {
            return juce::Typeface::createSystemTypefaceFor (data, (size_t) size);
        };
        faces[(int) Face::brand]       = make (UnboundedMedium_ttf, UnboundedMedium_ttfSize);
        faces[(int) Face::brandHeavy]  = make (UnboundedExtraBold_ttf, UnboundedExtraBold_ttfSize);
        faces[(int) Face::label]       = make (BarlowCondensedRegular_ttf, BarlowCondensedRegular_ttfSize);
        faces[(int) Face::labelMedium] = make (BarlowCondensedMedium_ttf, BarlowCondensedMedium_ttfSize);
        faces[(int) Face::labelSemi]   = make (BarlowCondensedSemiBold_ttf, BarlowCondensedSemiBold_ttfSize);
        faces[(int) Face::mono]        = make (SplineSansMonoRegular_ttf, SplineSansMonoRegular_ttfSize);
        faces[(int) Face::monoMedium]  = make (SplineSansMonoMedium_ttf, SplineSansMonoMedium_ttfSize);
    }

    juce::Font Fonts::get (Face f, float px, float trackingEm) const
    {
        const auto& face = faces[(int) f];
        juce::Font font = face != nullptr ? juce::Font (juce::FontOptions (face).withPointHeight (px))
                                          : juce::Font (juce::FontOptions().withPointHeight (px));
        // JUCE's tracking is a proportion of the font height (ascent + descent), CSS's
        // letter-spacing a proportion of the em (the point height)
        if (trackingEm != 0.0f && font.getHeight() > 0.0f)
            font = font.withExtraKerningFactor (trackingEm * px / font.getHeight());
        return font;
    }

    //==============================================================================
    LookAndFeel::LookAndFeel()
    {
        using namespace colours;
        setColour (juce::ResizableWindow::backgroundColourId, bg);
        setColour (juce::TooltipWindow::backgroundColourId, juce::Colour (0xf0241c10));
        setColour (juce::TooltipWindow::outlineColourId, amberDim);
        setColour (juce::TooltipWindow::textColourId, amberHot);
        setColour (juce::TextButton::textColourOffId, dim.withAlpha (1.0f));
        setColour (juce::TextButton::textColourOnId, txt);
    }

    void LookAndFeel::drawRotarySlider (juce::Graphics& g, int x, int y, int width, int height,
                                        float pos, float a0, float a1, juce::Slider&)
    {
        using namespace colours;
        // The slider's bounds keep a margin around the dial for the arc's glow
        // (Knob in Widgets.cpp): the dial is 84 % of the square.
        const auto box = juce::Rectangle<float> ((float) x, (float) y, (float) width, (float) height);
        const float d = juce::jmin (box.getWidth(), box.getHeight()) * 0.84f;
        const auto c = box.getCentre();
        const float r = d * 0.5f;
        const float k = d / 46.0f;              // proportions of the web knob (--knob-size: 46px)
        const float capR = r * (17.0f / 23.0f); // .k-cap: inset 6px
        const float ringW = r - capR + 1.5f * k;
        const float ringR = r - ringW * 0.5f;
        const float av = a0 + juce::jlimit (0.0f, 1.0f, pos) * (a1 - a0);

        const juce::PathStrokeType ringStroke (ringW, juce::PathStrokeType::curved, juce::PathStrokeType::butt);

        // 1. track: the unlit part of the 270-degree sweep (#37302699)
        {
            juce::Path track;
            track.addCentredArc (c.x, c.y, ringR, ringR, 0.0f, a0, a1, true);
            g.setColour (juce::Colour (0x99373026));
            g.strokePath (track, ringStroke);
        }

        // 2. value arc, amber, with a soft glow under it
        if (av > a0 + 0.01f)
        {
            juce::Path arc;
            arc.addCentredArc (c.x, c.y, ringR, ringR, 0.0f, a0, av, true);
            g.setColour (amber.withAlpha (0.06f));
            g.strokePath (arc, juce::PathStrokeType (ringW + 6.0f * k, juce::PathStrokeType::curved, juce::PathStrokeType::butt));
            g.setColour (amber.withAlpha (0.12f));
            g.strokePath (arc, juce::PathStrokeType (ringW + 2.5f * k, juce::PathStrokeType::curved, juce::PathStrokeType::butt));
            g.setColour (amber);
            g.strokePath (arc, ringStroke);
        }

        // 3. cap: drop shadow (0 3px 6px #000a), radial body, top inner highlight
        {
            const float sr = capR + 6.0f * k;
            const juce::Point<float> sc (c.x, c.y + 3.0f * k);
            juce::ColourGradient shadow (juce::Colour (0xaa000000), sc, juce::Colours::transparentBlack, sc.translated (sr, 0.0f), true);
            shadow.addColour ((capR - 2.0f * k) / sr, juce::Colour (0x99000000));
            g.setGradientFill (shadow);
            g.fillEllipse (sc.x - sr, sc.y - sr, sr * 2.0f, sr * 2.0f);

            const auto capBox = juce::Rectangle<float> (capR * 2.0f, capR * 2.0f).withCentre (c);
            const juce::Point<float> hot (capBox.getX() + capBox.getWidth() * 0.34f, capBox.getY() + capBox.getHeight() * 0.28f);
            juce::ColourGradient body (juce::Colour (0xff4d4335), hot, juce::Colour (0xff15110d), hot.translated (capR * 1.95f, 0.0f), true);
            body.addColour (0.6 / 1.0, juce::Colour (0xff241f18));
            g.setGradientFill (body);
            g.fillEllipse (capBox);

            juce::ColourGradient rim (juce::Colours::white.withAlpha (0.13f), c.x, capBox.getY(),
                                      juce::Colours::transparentWhite, c.x, capBox.getY() + capR * 0.9f, false);
            g.setGradientFill (rim);
            g.drawEllipse (capBox.reduced (0.5f), 1.0f * k);
        }

        // 4. pointer (.k-ind): amber-hot bar with a glow, rounded ends
        {
            const juce::Point<float> dir (std::sin (av), -std::cos (av));
            juce::Path bar;
            bar.startNewSubPath (c + dir * (capR * 0.28f));
            bar.lineTo (c + dir * (capR * 0.80f));
            g.setColour (amber.withAlpha (0.30f));
            g.strokePath (bar, juce::PathStrokeType (5.5f * k, juce::PathStrokeType::curved, juce::PathStrokeType::rounded));
            g.setColour (amberHot);
            g.strokePath (bar, juce::PathStrokeType (2.6f * k, juce::PathStrokeType::curved, juce::PathStrokeType::rounded));
        }
    }

    void LookAndFeel::drawToggleButton (juce::Graphics& g, juce::ToggleButton& b, bool hover, bool)
    {
        using namespace colours;
        // .toggle .sw: a 34 x 18 pill; the label follows it (letter-spaced caps, dim)
        const auto bounds = b.getLocalBounds().toFloat();
        const float h = juce::jmin (bounds.getHeight(), 20.0f);
        const float w = h * 34.0f / 18.0f;
        const auto pill = juce::Rectangle<float> (bounds.getX() + 1.0f, bounds.getCentreY() - h * 0.5f, w, h);
        const bool on = b.getToggleState();
        const float rr = h * 0.5f;

        g.setColour (on ? juce::Colour (0xff3d2c12) : juce::Colour (0xff131009));
        g.fillRoundedRectangle (pill, rr);
        // inset 0 2px 4px #000b
        juce::ColourGradient inset (juce::Colour (0xaa000000), pill.getCentreX(), pill.getY(),
                                    juce::Colours::transparentBlack, pill.getCentreX(), pill.getY() + h * 0.45f, false);
        g.setGradientFill (inset);
        g.fillRoundedRectangle (pill, rr);
        g.setColour (hover ? btnHover : line);
        g.drawRoundedRectangle (pill.reduced (0.5f), rr - 0.5f, 1.0f);

        const float t = h - 6.0f;   // thumb diameter (12 of 18)
        const auto thumb = juce::Rectangle<float> (t, t).withCentre ({ on ? pill.getRight() - 3.0f - t * 0.5f
                                                                          : pill.getX() + 3.0f + t * 0.5f,
                                                                       pill.getCentreY() });
        if (on)
        {
            juce::ColourGradient halo (amber.withAlpha (0.55f), thumb.getCentre(), amber.withAlpha (0.0f),
                                       thumb.getCentre().translated (t * 1.1f, 0.0f), true);
            g.setGradientFill (halo);
            g.fillEllipse (thumb.expanded (t * 0.6f));
            g.setColour (amber);
            g.fillEllipse (thumb);
            g.setColour (juce::Colours::white.withAlpha (0.25f));
            g.drawEllipse (thumb.reduced (1.0f), 0.8f);
        }
        else
        {
            g.setGradientFill (juce::ColourGradient (juce::Colour (0xff7a6c58), thumb.getCentreX(), thumb.getY(),
                                                     juce::Colour (0xff4a4136), thumb.getCentreX(), thumb.getBottom(), false));
            g.fillEllipse (thumb);
        }

        const auto textArea = bounds.withLeft (pill.getRight() + 8.0f);
        g.setColour (dim);
        g.setFont (font (Face::labelMedium, 14.0f, 0.12f));
        g.drawText (b.getButtonText(), textArea, juce::Justification::centredLeft, false);
    }

    void LookAndFeel::drawButtonBackground (juce::Graphics& g, juce::Button& b, const juce::Colour&,
                                            bool hover, bool down)
    {
        drawButtonFace (g, b.getLocalBounds().toFloat(), 6.0f, hover && b.isEnabled(), down, false);
    }

    void LookAndFeel::drawButtonText (juce::Graphics& g, juce::TextButton& b, bool hover, bool down)
    {
        using namespace colours;
        g.setColour (hover || down ? txt : dim.withAlpha (1.0f));
        g.setFont (getTextButtonFont (b, b.getHeight()));
        auto area = b.getLocalBounds().toFloat();
        if (down) area.translate (0.0f, 0.5f);
        g.drawText (b.getButtonText(), area, juce::Justification::centred, false);
    }

    juce::Font LookAndFeel::getTextButtonFont (juce::TextButton&, int buttonHeight)
    {
        return font (Face::labelSemi, juce::jmin (16.0f, (float) buttonHeight * 0.62f));
    }

    juce::TextLayout LookAndFeel::layoutTooltip (const juce::String& text) const
    {
        juce::AttributedString s;
        s.setJustification (juce::Justification::centredLeft);
        s.append (text, font (Face::label, 14.0f, 0.02f), colours::amberHot);
        juce::TextLayout tl;
        tl.createLayoutWithBalancedLineLengths (s, 300.0f);
        return tl;
    }

    juce::Rectangle<int> LookAndFeel::getTooltipBounds (const juce::String& tipText, juce::Point<int> screenPos,
                                                        juce::Rectangle<int> parentArea)
    {
        const auto tl = layoutTooltip (tipText);
        const auto w = (int) std::ceil (tl.getWidth() + 20.0f);
        const auto h = (int) std::ceil (tl.getHeight() + 12.0f);
        return juce::Rectangle<int> (screenPos.x > parentArea.getCentreX() ? screenPos.x - (w + 12) : screenPos.x + 20,
                                     screenPos.y > parentArea.getCentreY() ? screenPos.y - (h + 6) : screenPos.y + 8,
                                     w, h)
            .constrainedWithin (parentArea);
    }

    void LookAndFeel::drawTooltip (juce::Graphics& g, const juce::String& text, int width, int height)
    {
        const auto area = juce::Rectangle<float> ((float) width, (float) height);
        g.setColour (findColour (juce::TooltipWindow::backgroundColourId));
        g.fillRoundedRectangle (area, 6.0f);
        g.setColour (findColour (juce::TooltipWindow::outlineColourId));
        g.drawRoundedRectangle (area.reduced (0.5f), 6.0f, 1.0f);
        layoutTooltip (text).draw (g, area.reduced (10.0f, 6.0f));
    }

    void LookAndFeel::drawCornerResizer (juce::Graphics& g, int w, int h, bool isMouseOver, bool isMouseDragging)
    {
        // three engraved diagonal grooves, amber while dragged
        const auto colour = (isMouseOver || isMouseDragging) ? colours::amber.withAlpha (0.8f) : colours::line.brighter (0.25f);
        const float s = (float) juce::jmin (w, h);
        for (int i = 1; i <= 3; ++i)
        {
            const float o = s * (float) i / 4.0f;
            g.setColour (juce::Colours::black.withAlpha (0.5f));
            g.drawLine ((float) w - o, (float) h + 0.8f, (float) w + 0.8f, (float) h - o, 1.6f);
            g.setColour (colour);
            g.drawLine ((float) w - o, (float) h - 0.6f, (float) w - 0.6f, (float) h - o, 1.0f);
        }
    }

    //==============================================================================
    float physicalScale (juce::Graphics& g)
    {
        return juce::jmax (0.1f, g.getInternalContext().getPhysicalPixelScaleFactor());
    }

    void drawLed (juce::Graphics& g, juce::Point<float> c, float radius, juce::Colour colour, bool lit, float glow)
    {
        const auto box = juce::Rectangle<float> (radius * 2.0f, radius * 2.0f).withCentre (c);
        if (! lit)
        {
            // background #3a3128, inset 0 1px 2px #0009
            g.setColour (colours::ledOff);
            g.fillEllipse (box);
            g.setGradientFill (juce::ColourGradient (juce::Colour (0x99000000), c.x, box.getY(),
                                                     juce::Colours::transparentBlack, c.x, c.y + radius * 0.3f, false));
            g.fillEllipse (box);
            return;
        }
        // box-shadow 0 0 8px 2px colour/50 %, inset 0 0 2px #fff8
        const float haloR = radius * 3.4f;
        juce::ColourGradient halo (colour.withAlpha (0.45f * glow), c, colour.withAlpha (0.0f), c.translated (haloR, 0.0f), true);
        halo.addColour (0.35, colour.withAlpha (0.22f * glow));
        g.setGradientFill (halo);
        g.fillEllipse (box.withSizeKeepingCentre (haloR * 2.0f, haloR * 2.0f));
        g.setColour (colour);
        g.fillEllipse (box);
        juce::ColourGradient core (juce::Colours::white.withAlpha (0.55f), c.translated (-radius * 0.25f, -radius * 0.3f),
                                   juce::Colours::white.withAlpha (0.0f), c.translated (radius * 0.75f, 0.0f), true);
        g.setGradientFill (core);
        g.fillEllipse (box);
    }

    void drawRecessed (juce::Graphics& g, juce::Rectangle<float> r, float cr, juce::Colour fill)
    {
        // lower highlight (0 1px 0 #ffffff12)
        g.setColour (juce::Colours::white.withAlpha (0.07f));
        g.fillRoundedRectangle (r.translated (0.0f, 1.0f), cr);
        g.setColour (fill);
        g.fillRoundedRectangle (r, cr);
        // inset 0 2px 8px #000d: a dark band fading down from the top edge
        {
            juce::Graphics::ScopedSaveState s (g);
            juce::Path clip;
            clip.addRoundedRectangle (r, cr);
            g.reduceClipRegion (clip);
            const float depth = juce::jmin (10.0f, r.getHeight() * 0.45f);
            g.setGradientFill (juce::ColourGradient (juce::Colour (0xcc000000), r.getX(), r.getY(),
                                                     juce::Colours::transparentBlack, r.getX(), r.getY() + depth, false));
            g.fillRect (r.withHeight (depth));
            const float side = juce::jmin (6.0f, r.getWidth() * 0.1f);
            g.setGradientFill (juce::ColourGradient (juce::Colour (0x66000000), r.getX(), r.getY(),
                                                     juce::Colours::transparentBlack, r.getX() + side, r.getY(), false));
            g.fillRect (r.withWidth (side));
            g.setGradientFill (juce::ColourGradient (juce::Colour (0x66000000), r.getRight(), r.getY(),
                                                     juce::Colours::transparentBlack, r.getRight() - side, r.getY(), false));
            g.fillRect (r.withLeft (r.getRight() - side));
        }
        g.setColour (juce::Colours::black);
        g.drawRoundedRectangle (r.reduced (0.5f), cr, 1.0f);
    }

    void drawButtonFace (juce::Graphics& g, juce::Rectangle<float> r, float cr, bool hover, bool down,
                         bool latched, juce::Colour latchedBorder)
    {
        using namespace colours;
        if (down) r.translate (0.0f, 0.6f);
        // drop shadow 0 2px 6px #0006 (kept tight: buttons sit close together)
        g.setColour (juce::Colours::black.withAlpha (0.35f));
        g.fillRoundedRectangle (r.translated (0.0f, 1.2f), cr);
        const auto top = latched ? juce::Colour (0xff3a2f1e) : btnTop;
        const auto bottom = latched ? juce::Colour (0xff262015) : btnBottom;
        g.setGradientFill (juce::ColourGradient (top, r.getX(), r.getY(), bottom, r.getX(), r.getBottom(), false));
        g.fillRoundedRectangle (r, cr);
        // inset 0 1px 0 #ffffff0d
        g.setColour (juce::Colours::white.withAlpha (0.05f));
        g.drawLine (r.getX() + cr, r.getY() + 1.0f, r.getRight() - cr, r.getY() + 1.0f, 1.0f);
        g.setColour (latched ? latchedBorder : (hover ? btnHover : line));
        g.drawRoundedRectangle (r.reduced (0.5f), cr, 1.0f);
    }

    void drawScrew (juce::Graphics& g, juce::Point<float> c, float radius, float angle)
    {
        const auto head = juce::Rectangle<float> (radius * 2.0f, radius * 2.0f).withCentre (c);
        // countersink in the panel, then the head's own shadow (0 1px 2px #000a)
        g.setColour (juce::Colours::black.withAlpha (0.35f));
        g.fillEllipse (head.expanded (radius * 0.28f));
        g.setColour (juce::Colours::black.withAlpha (0.55f));
        g.fillEllipse (head.translated (0.0f, radius * 0.18f).expanded (radius * 0.06f));
        // radial-gradient(circle at 35% 30%, #6a5f4e, #2c2620 65%, #171310)
        const juce::Point<float> hot (head.getX() + head.getWidth() * 0.35f, head.getY() + head.getHeight() * 0.30f);
        juce::ColourGradient metal (juce::Colour (0xff6a5f4e), hot, juce::Colour (0xff171310), hot.translated (radius * 1.75f, 0.0f), true);
        metal.addColour (0.65, juce::Colour (0xff2c2620));
        g.setGradientFill (metal);
        g.fillEllipse (head);
        // the slot: a dark groove with a faint lit lower lip
        const auto slot = juce::Rectangle<float> (radius * 1.9f, radius * 0.30f).withCentre (c);
        const auto turn = juce::AffineTransform::rotation (angle, c.x, c.y);
        juce::Path groove;
        groove.addRoundedRectangle (slot, radius * 0.08f);
        juce::Path lip;
        lip.addRectangle (slot.withY (slot.getBottom()).withHeight (radius * 0.12f).reduced (radius * 0.18f, 0.0f));
        g.setColour (juce::Colours::white.withAlpha (0.10f));
        g.fillPath (lip, turn);
        g.setColour (juce::Colour (0xd0000000));
        g.fillPath (groove, turn);
        // inset 0 0 2px #000: a dark rim
        g.setColour (juce::Colours::black.withAlpha (0.6f));
        g.drawEllipse (head.reduced (0.4f), 0.8f);
    }

    //==============================================================================
    namespace
    {
        /** Separable gaussian blur of a single-channel software image (sigma in pixels). */
        void blurSingleChannel (juce::Image& img, float sigma)
        {
            const int w = img.getWidth(), h = img.getHeight();
            if (w <= 0 || h <= 0 || sigma < 0.3f)
                return;
            const int half = juce::jmax (1, (int) std::ceil (sigma * 3.0f));
            std::vector<float> kernel ((size_t) (half * 2 + 1));
            float sum = 0.0f;
            for (int i = -half; i <= half; ++i)
                sum += kernel[(size_t) (i + half)] = std::exp (-(float) (i * i) / (2.0f * sigma * sigma));
            for (auto& v : kernel)
                v /= sum;

            std::vector<float> buf ((size_t) (w * h)), tmp ((size_t) (w * h));
            {
                const juce::Image::BitmapData data (img, juce::Image::BitmapData::readOnly);
                for (int y = 0; y < h; ++y)
                    for (int x = 0; x < w; ++x)
                        buf[(size_t) (y * w + x)] = (float) *data.getPixelPointer (x, y);
            }
            for (int y = 0; y < h; ++y)
                for (int x = 0; x < w; ++x)
                {
                    float acc = 0.0f;
                    for (int i = -half; i <= half; ++i)
                    {
                        const int xx = x + i;
                        if (xx >= 0 && xx < w)
                            acc += buf[(size_t) (y * w + xx)] * kernel[(size_t) (i + half)];
                    }
                    tmp[(size_t) (y * w + x)] = acc;
                }
            const juce::Image::BitmapData data (img, juce::Image::BitmapData::writeOnly);
            for (int y = 0; y < h; ++y)
                for (int x = 0; x < w; ++x)
                {
                    float acc = 0.0f;
                    for (int i = -half; i <= half; ++i)
                    {
                        const int yy = y + i;
                        if (yy >= 0 && yy < h)
                            acc += tmp[(size_t) (yy * w + x)] * kernel[(size_t) (i + half)];
                    }
                    *data.getPixelPointer (x, y) = (juce::uint8) juce::jlimit (0, 255, (int) std::lround (acc));
                }
        }
    }

    void GlowText::draw (juce::Graphics& g, const juce::String& newText, const juce::Font& newFont,
                         juce::Rectangle<float> newArea, juce::Justification newJust,
                         juce::Colour textColour, juce::Colour glowColour, float newRadius)
    {
        const float ps = physicalScale (g);
        if (newText.isEmpty())
            return;
        if (newText != text || newFont != font || newArea != area || newJust != just
            || newRadius != radius || ps != scale || halo.isNull())
        {
            text = newText;
            font = newFont;
            area = newArea;
            just = newJust;
            radius = newRadius;
            scale = ps;
            haloArea = area.expanded (radius * 1.6f);
            // The halo is pure low frequencies: rendered and blurred at a coarse scale
            // (sigma = 2 px) then stretched with bilinear filtering. Blurring at device
            // resolution would cost tens of ms per text change at 200 % x 150 %.
            haloScale = juce::jmin (ps, 4.0f / juce::jmax (1.0f, radius));
            const int iw = juce::jmax (1, (int) std::ceil (haloArea.getWidth() * haloScale));
            const int ih = juce::jmax (1, (int) std::ceil (haloArea.getHeight() * haloScale));
            juce::Image mask (juce::Image::SingleChannel, iw, ih, true, juce::SoftwareImageType());
            {
                juce::Graphics mg (mask);
                mg.addTransform (juce::AffineTransform::translation (-haloArea.getX(), -haloArea.getY()).scaled (haloScale));
                mg.setColour (juce::Colours::white);
                mg.setFont (font);
                mg.drawText (text, area, just, false);
            }
            blurSingleChannel (mask, radius * 0.5f * haloScale);   // CSS blur radius = 2 sigma
            halo = mask;
        }
        {
            juce::Graphics::ScopedSaveState s (g);
            g.setImageResamplingQuality (juce::Graphics::mediumResamplingQuality);
            g.setColour (glowColour);
            g.drawImageTransformed (halo, juce::AffineTransform::scale (1.0f / haloScale).translated (haloArea.getX(), haloArea.getY()), true);
        }
        g.setColour (textColour);
        g.setFont (font);
        g.drawText (text, area, just, false);
    }
}
